import Rigid.AffinoidAlgebra.CompletedTensorProduct

set_option linter.style.header false

/-!
# Rational localizations of strict affinoid algebras

This module records the algebraic part of a rational affinoid domain. For a rational datum
`(g; f₁, ..., fₙ)`, the ambient algebra is obtained by adjoining bounded variables to a chosen
presentation of `A`; quotienting by `g Tᵢ - fᵢ` gives the usual rational localization presentation.
-/

universe u v

namespace Rigid

variable (K : Type u) [NontriviallyNormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable {A : Type v} [CommRing A] [Algebra K A]

namespace AffinoidPresentation

/-- The ambient affinoid algebra obtained by adjoining `n` Tate variables to `P`. -/
noncomputable abbrev rationalAmbient (P : AffinoidPresentation K A) (n : ℕ) : Type u :=
  CompletedTensorProduct K P (tateAlgebraPresentation K n)

noncomputable instance rationalAmbientCommRing (P : AffinoidPresentation K A) (n : ℕ) :
    CommRing (rationalAmbient K P n) :=
  inferInstance

noncomputable instance rationalAmbientAlgebra (P : AffinoidPresentation K A) (n : ℕ) :
    Algebra K (rationalAmbient K P n) :=
  inferInstance

/-- The ideal generated by the rational localization equations. -/
noncomputable def rationalRelationIdeal (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) : Ideal (rationalAmbient K P n) :=
  Ideal.span (Set.range fun i ↦
    includeLeft K P (tateAlgebraPresentation K n) g *
        includeRight K P (tateAlgebraPresentation K n)
          (tateVariable K (Fin n) i) -
      includeLeft K P (tateAlgebraPresentation K n) (f i))

/-- The rational localization associated with a chosen presentation and rational datum. -/
noncomputable abbrev rationalLocalization (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) : Type u :=
  rationalAmbient K P n ⧸ rationalRelationIdeal K P g f

noncomputable instance rationalLocalizationCommRing (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) : CommRing (rationalLocalization K P g f) :=
  inferInstance

noncomputable instance rationalLocalizationAlgebra (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) : Algebra K (rationalLocalization K P g f) :=
  inferInstance

/-- Rational localizations of affinoid algebras are affinoid. -/
theorem rationalLocalization_isAffinoid (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) :
    IsAffinoidAlgebra K (rationalLocalization K P g f) :=
  IsAffinoidAlgebra.quotient K
    (completedTensorProduct_isAffinoid K P (tateAlgebraPresentation K n))
    (rationalRelationIdeal K P g f)

/-- The canonical map from the original affinoid algebra to its rational localization. -/
noncomputable def rationalLocalizationMap (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) : A →ₐ[K] rationalLocalization K P g f :=
  (Ideal.Quotient.mkₐ K (rationalRelationIdeal K P g f)).comp
    (includeLeft K P (tateAlgebraPresentation K n))

/-- The canonical map sending the newly adjoined Tate variables into the rational localization. -/
noncomputable def rationalLocalizationVariable (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) : Fin n → rationalLocalization K P g f :=
  fun i ↦ Ideal.Quotient.mk (rationalRelationIdeal K P g f)
    (includeRight K P (tateAlgebraPresentation K n)
      (tateVariable K (Fin n) i))

@[simp]
theorem rationalLocalization_relation (P : AffinoidPresentation K A)
    {n : ℕ} (g : A) (f : Fin n → A) (i : Fin n) :
    rationalLocalizationMap K P g f g * rationalLocalizationVariable K P g f i =
      rationalLocalizationMap K P g f (f i) := by
  unfold rationalLocalizationMap rationalLocalizationVariable
  change (Ideal.Quotient.mkₐ K (rationalRelationIdeal K P g f))
      (includeLeft K P (tateAlgebraPresentation K n) g) *
      (Ideal.Quotient.mkₐ K (rationalRelationIdeal K P g f))
        (includeRight K P (tateAlgebraPresentation K n)
          (tateVariable K (Fin n) i)) =
    (Ideal.Quotient.mkₐ K (rationalRelationIdeal K P g f))
      (includeLeft K P (tateAlgebraPresentation K n) (f i))
  rw [← map_mul, ← sub_eq_zero, ← map_sub]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  apply Ideal.subset_span
  exact ⟨i, rfl⟩

/-- Maps from a rational localization into an affinoid algebra are determined by the map on the
base algebra and the images of the rational variables. -/
theorem rationalLocalization_algHom_ext
    {C : Type*} [CommRing C] [Algebra K C]
    (P : AffinoidPresentation K A) {n : ℕ} (g : A) (f : Fin n → A)
    (R : AffinoidPresentation K C) (φ ψ : rationalLocalization K P g f →ₐ[K] C)
    (hbase : φ.comp (rationalLocalizationMap K P g f) =
      ψ.comp (rationalLocalizationMap K P g f))
    (hvar : ∀ i, φ (rationalLocalizationVariable K P g f i) =
      ψ (rationalLocalizationVariable K P g f i)) :
    φ = ψ := by
  let T := tateAlgebraPresentation K n
  let q := Ideal.Quotient.mkₐ K (rationalRelationIdeal K P g f)
  apply (AlgHom.cancel_right (Ideal.Quotient.mkₐ_surjective K
    (rationalRelationIdeal K P g f))).mp
  apply completedTensorProduct_algHom_ext K P T R
  · simpa [q, T, rationalLocalizationMap, AlgHom.comp_assoc] using hbase
  · apply tateAlgebra_algHom_ext K n R
    intro i
    simpa [q, T, rationalLocalizationVariable, AlgHom.comp_apply] using hvar i

/-- The bounded universal map out of a rational localization into a presented affinoid algebra. -/
noncomputable def rationalLocalizationLift
    {C : Type*} [CommRing C] [Algebra K C]
    (P : AffinoidPresentation K A) {n : ℕ} (g : A) (f : Fin n → A)
    (R : AffinoidPresentation K C) (h : A →ₐ[K] C) (x : Fin n → C)
    (hx : letI : NormedCommRing C := R.residueNormedCommRing K C
      ∀ i, IsPowerBounded (x i))
    (hrel : ∀ i, h g * x i = h (f i)) :
    letI : NormedCommRing C := R.residueNormedCommRing K C
    letI : NormedAlgebra K C := R.residueNormedAlgebra K C
    letI : CompleteSpace C := R.residueCompleteSpace K C
    letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
    rationalLocalization K P g f →ₐ[K] C := by
  letI : NormedCommRing C := R.residueNormedCommRing K C
  letI : NormedAlgebra K C := R.residueNormedAlgebra K C
  letI : CompleteSpace C := R.residueCompleteSpace K C
  letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
  let T := tateAlgebraPresentation K n
  let e := Classical.choose
    (existsUnique_continuousAlgHom_of_isPowerBounded (K := K) x hx).exists
  have he : ∀ i, e (tateVariable K (Fin n) i) = x i :=
    Classical.choose_spec
      (existsUnique_continuousAlgHom_of_isPowerBounded (K := K) x hx).exists
  have he' : ∀ i, e.toAlgHom (tateVariable K (Fin n) i) = x i := by
    intro i
    exact he i
  let ambient := completedTensorLift K P T R h e.toAlgHom
  have hker : rationalRelationIdeal K P g f ≤ RingHom.ker ambient.toRingHom := by
    rw [rationalRelationIdeal, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    change ambient
        (includeLeft K P T g * includeRight K P T (tateVariable K (Fin n) i) -
          includeLeft K P T (f i)) = 0
    rw [map_sub, map_mul]
    change (ambient.comp (includeLeft K P T)) g *
        (ambient.comp (includeRight K P T)) (tateVariable K (Fin n) i) -
      (ambient.comp (includeLeft K P T)) (f i) = 0
    have hleft := completedTensorLift_comp_includeLeft K P T R h e.toAlgHom
    have hright := completedTensorLift_comp_includeRight K P T R h e.toAlgHom
    rw [hleft, hright, he', hrel, sub_self]
  exact Ideal.Quotient.liftₐ (rationalRelationIdeal K P g f)
    ambient (fun a ha ↦ by
      have ha' := hker ha
      change ambient a = 0 at ha'
      exact ha')

@[simp]
theorem rationalLocalizationLift_comp_map
    {C : Type*} [CommRing C] [Algebra K C]
    (P : AffinoidPresentation K A) {n : ℕ} (g : A) (f : Fin n → A)
    (R : AffinoidPresentation K C) (h : A →ₐ[K] C) (x : Fin n → C)
    (hx : letI : NormedCommRing C := R.residueNormedCommRing K C
      ∀ i, IsPowerBounded (x i))
    (hrel : ∀ i, h g * x i = h (f i)) :
    letI : NormedCommRing C := R.residueNormedCommRing K C
    letI : NormedAlgebra K C := R.residueNormedAlgebra K C
    letI : CompleteSpace C := R.residueCompleteSpace K C
    letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
    (rationalLocalizationLift K P g f R h x hx hrel).comp
        (rationalLocalizationMap K P g f) = h := by
  letI : NormedCommRing C := R.residueNormedCommRing K C
  letI : NormedAlgebra K C := R.residueNormedAlgebra K C
  letI : CompleteSpace C := R.residueCompleteSpace K C
  letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
  apply (AlgHom.cancel_right (P.toAlgHom_surjective K A)).mp
  ext a
  dsimp [rationalLocalizationMap, rationalLocalizationLift]
  exact congrArg (fun q : A →ₐ[K] C ↦ q (AffinoidPresentation.toAlgHom K A P a))
    (completedTensorLift_comp_includeLeft K P (tateAlgebraPresentation K n) R h
      (Classical.choose
        (existsUnique_continuousAlgHom_of_isPowerBounded (K := K) x hx).exists).toAlgHom)

@[simp]
theorem rationalLocalizationLift_variable
    {C : Type*} [CommRing C] [Algebra K C]
    (P : AffinoidPresentation K A) {n : ℕ} (g : A) (f : Fin n → A)
    (R : AffinoidPresentation K C) (h : A →ₐ[K] C) (x : Fin n → C)
    (hx : letI : NormedCommRing C := R.residueNormedCommRing K C
      ∀ i, IsPowerBounded (x i))
    (hrel : ∀ i, h g * x i = h (f i)) (i : Fin n) :
    letI : NormedCommRing C := R.residueNormedCommRing K C
    letI : NormedAlgebra K C := R.residueNormedAlgebra K C
    letI : CompleteSpace C := R.residueCompleteSpace K C
    letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
    rationalLocalizationLift K P g f R h x hx hrel
        (rationalLocalizationVariable K P g f i) = x i := by
  letI : NormedCommRing C := R.residueNormedCommRing K C
  letI : NormedAlgebra K C := R.residueNormedAlgebra K C
  letI : CompleteSpace C := R.residueCompleteSpace K C
  letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
  unfold rationalLocalizationLift rationalLocalizationVariable
  rw [Ideal.Quotient.liftₐ_apply, Ideal.Quotient.lift_mk]
  have hright := congrArg (fun q : TateAlgebra K (Fin n) →ₐ[K] C ↦
      q (tateVariable K (Fin n) i))
    (completedTensorLift_comp_includeRight K P (tateAlgebraPresentation K n) R h
      (Classical.choose
        (existsUnique_continuousAlgHom_of_isPowerBounded (K := K) x hx).exists).toAlgHom)
  change ((completedTensorLift K P (tateAlgebraPresentation K n) R h
    (Classical.choose
      (existsUnique_continuousAlgHom_of_isPowerBounded (K := K) x hx).exists).toAlgHom).comp
      (includeRight K P (tateAlgebraPresentation K n)))
      (tateVariable K (Fin n) i) = x i
  rw [hright]
  simpa using Classical.choose_spec
    (existsUnique_continuousAlgHom_of_isPowerBounded (K := K) x hx).exists i

/-- The rational localization represents bounded solutions of the equations `g Tᵢ = fᵢ` in
affinoid target algebras. -/
theorem existsUnique_algHom_from_rationalLocalization
    {C : Type*} [CommRing C] [Algebra K C]
    (P : AffinoidPresentation K A) {n : ℕ} (g : A) (f : Fin n → A)
    (R : AffinoidPresentation K C) (h : A →ₐ[K] C) (x : Fin n → C)
    (hx : letI : NormedCommRing C := R.residueNormedCommRing K C
      ∀ i, IsPowerBounded (x i))
    (hrel : ∀ i, h g * x i = h (f i)) :
    letI : NormedCommRing C := R.residueNormedCommRing K C
    letI : NormedAlgebra K C := R.residueNormedAlgebra K C
    letI : CompleteSpace C := R.residueCompleteSpace K C
    letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
    ∃! φ : rationalLocalization K P g f →ₐ[K] C,
      φ.comp (rationalLocalizationMap K P g f) = h ∧
        ∀ i, φ (rationalLocalizationVariable K P g f i) = x i := by
  letI : NormedCommRing C := R.residueNormedCommRing K C
  letI : NormedAlgebra K C := R.residueNormedAlgebra K C
  letI : CompleteSpace C := R.residueCompleteSpace K C
  letI : IsUltrametricDist C := R.residueIsUltrametricDist K C
  refine ⟨rationalLocalizationLift K P g f R h x hx hrel,
    ⟨rationalLocalizationLift_comp_map K P g f R h x hx hrel,
      rationalLocalizationLift_variable K P g f R h x hx hrel⟩, ?_⟩
  intro φ hφ
  apply rationalLocalization_algHom_ext K P g f R
  · rw [hφ.1, rationalLocalizationLift_comp_map K P g f R h x hx hrel]
  · intro i
    rw [hφ.2 i, rationalLocalizationLift_variable K P g f R h x hx hrel i]

end AffinoidPresentation

end Rigid
